import { defineConfig } from "vitest/config";
import { resolve } from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./tests/setup.ts"],
    include: ["src/**/*.test.{ts,tsx}", "tests/**/*.test.{ts,tsx}"],
    exclude: [
      "node_modules",
      "dist",
      "tests/e2e",
      "src/components/atoms",
      "src/components/molecules/FormField",
      "src/components/templates",
      ".next",
      ".expo",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov", "html"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.types.ts",
        "src/**/*.d.ts",
        "src/types/**",
        "src/App.tsx",
        "src/proxy.ts",
        "src/proxy/**",
        "src/lib/analytics.ts",
        "src/lib/api-client.ts",
        "src/lib/auth.ts",
        "src/lib/auth/**",
        "src/lib/db/**",
        "src/lib/db.ts",
        "src/lib/logger.ts",
        "src/lib/structured-data.tsx",
        "src/context/**",
        "src/contracts/**",
        "src/app/**",
        "src/infrastructure/**",
        "src/components/ErrorBoundary.tsx",
        "src/components/atoms/HexButton.tsx",
        "src/components/atoms/ProgressHex.tsx",
        "src/components/organisms/HiveProjectionCard.tsx",
        "src/components/organisms/MainTemplate.tsx",
        "src/components/organisms/MetricCard.tsx",
        "src/components/organisms/Sidebar.tsx",
        "src/components/organisms/StatsChart.tsx",
        "src/components/organisms/TaskBoard.tsx",
        "src/components/molecules/AuthModal.tsx",
        "src/components/molecules/AuthButton.tsx",

      ],
      thresholds: {
        statements: 80,
        branches: 74,
        functions: 60,
        lines: 80,
      },
    },
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
});
